name: q_furniture_app
description: "QFurniture, Quins Group ecommerce app."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.5.1     
  go_router: ^14.2.3 
  intl: ^0.19.0
  cached_network_image: ^3.3.1
  http: ^1.2.0
  shimmer: ^3.0.0
  url_launcher: ^6.2.5

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^2.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  assets:
    - assets/images/
    # Product images (each subdirectory must be listed; Flutter does not recurse)
    - assets/products/031/
    - assets/products/031071/
    - assets/products/031089/
    - assets/products/032042/
    - assets/products/033/
    - assets/products/033091/
    - assets/products/041/
    - assets/products/042/
    - assets/products/044/
    - assets/products/055/
    - assets/products/058/
    - assets/products/059/
    - assets/products/069/
    - assets/products/071/
    - assets/products/086/
    - assets/products/089/
    - assets/products/091/
    - assets/products/1051/
    - assets/products/1052/
    - assets/products/1053/
    - assets/products/1055/
    - assets/products/1057/
    - assets/products/1058/
    - assets/products/1062/
    - assets/products/1062.1/
    - assets/products/1062.6/
    - assets/products/1063/
    - assets/products/10631115-6/
    - assets/products/10631115-6-1/
    - assets/products/1064/
    - assets/products/1064_1115_2/
    - assets/products/1064_1115_4/
    - assets/products/1065/
    - assets/products/1065.1/
    - assets/products/1065_eve_2/
    - assets/products/1066/
    - assets/products/1067/
    - assets/products/1067.1/
    - assets/products/1073/
    - assets/products/10731074-2/
    - assets/products/10731074-4/
    - assets/products/10731075-2/
    - assets/products/10731075-4/
    - assets/products/1074/
    - assets/products/1075/
    - assets/products/1083/
    - assets/products/10831074-4/
    - assets/products/10831074-6/
    - assets/products/10831075-4/
    - assets/products/10831075-6/
    - assets/products/110/
    - assets/products/110041/
    - assets/products/110071/
    - assets/products/1104/
    - assets/products/123/
    - assets/products/123042/
    - assets/products/123069/
    - assets/products/124/
    - assets/products/124041/
    - assets/products/124071/
    - assets/products/125/
    - assets/products/128/
    - assets/products/128041/
    - assets/products/128071/
    - assets/products/128089/
    - assets/products/129/
    - assets/products/129042/
    - assets/products/129069/
    - assets/products/132/
    - assets/products/132042/
    - assets/products/132069/
    - assets/products/133/
    - assets/products/133108/
    - assets/products/134/
    - assets/products/134042/
    - assets/products/134069/
    - assets/products/139142/
    - assets/products/148/
    - assets/products/219/
    - assets/products/240/
    - assets/products/321/
    - assets/products/322/
    - assets/products/33630/
    - assets/products/33698/
    - assets/products/345/
    - assets/products/354/
    - assets/products/355/
    - assets/products/360/
    - assets/products/392/
    - assets/products/393/
    - assets/products/398/
    - assets/products/41368/
    - assets/products/427/
    - assets/products/427431/
    - assets/products/428/
    - assets/products/428432/
    - assets/products/431/
    - assets/products/432/
    - assets/products/468/
    - assets/products/542/
    - assets/products/545/
    - assets/products/545535/
    - assets/products/546/
    - assets/products/549/
    - assets/products/700_701_702_703_704_705/
    - assets/products/707/
    - assets/products/708/
    - assets/products/709-710-711/
    - assets/products/714/
    - assets/products/719/
    - assets/products/720/
    - assets/products/721/
    - assets/products/722/
    - assets/products/724/
    - assets/products/726-727/
    - assets/products/728-729/
    - assets/products/730/
    - assets/products/732/
    - assets/products/733/
    - assets/products/734/
    - assets/products/735/
    - assets/products/738/
    - assets/products/739-bundle/
    - assets/products/742-bundle/
    - assets/products/744-bundle/
    - assets/products/745-bundle/
    - assets/products/746/
    - assets/products/747/
    - assets/products/748/
    - assets/products/748-bundle/
    - assets/products/749-bundle/
    - assets/products/750-bundle/
    - assets/products/752-bundle/
    - assets/products/755-bundle/
    - assets/products/756/
    - assets/products/758/
    - assets/products/759-bundle/
    - assets/products/760-bundle/
    - assets/products/761-bundle/
    - assets/products/762-bundle/
    - assets/products/763/
    - assets/products/764-Bundle/
    - assets/products/765/
    - assets/products/767/
    - assets/products/769/
    - assets/products/770/
    - assets/products/772/
    - assets/products/773/
    - assets/products/775/
    - assets/products/778-bundle/
    - assets/products/779/
    - assets/products/780/
    - assets/products/784/
    - assets/products/785/
    - assets/products/786/
    - assets/products/787/
    - assets/products/789/
    - assets/products/790/
    - assets/products/791/
    - assets/products/792/
    - assets/products/794/
    - assets/products/795/
    - assets/products/796/
    - assets/products/797/
    - assets/products/798/
    - assets/products/800/
    - assets/products/802/
    - assets/products/8020/
    - assets/products/803/
    - assets/products/8030/
    - assets/products/805/
    - assets/products/806/
    - assets/products/830/
    - assets/products/832/
    - assets/products/833/
    - assets/products/834/
    - assets/products/840/
    - assets/products/841/
    - assets/products/842/
    - assets/products/865/
    - assets/products/ESP-U-EVE/
    - assets/products/ESP___8211__3_EVE/
    - assets/products/MAC-DIR-SET-3/
    - assets/products/QF-ARI-3PCE/
    - assets/products/QF-ARI-SOFA-1__02_ABWH/
    - assets/products/QF-BE-2/
    - assets/products/QF-CLA-1SF/
    - assets/products/QF-CLA-2SF/
    - assets/products/QF-CLA-C12/
    - assets/products/QF-CLA-SET-3/
    - assets/products/QF-CLA-SET-4/
    - assets/products/QF-DIR01_23/
    - assets/products/QF-DRC-ST-2/
    - assets/products/QF-ESP-2/
    - assets/products/QF-ESP-3/
    - assets/products/QF-ESP-8F/
    - assets/products/QF-ESP-U/
    - assets/products/QF-EVE-2DIR/
    - assets/products/QF-EVE-DIR/
    - assets/products/QF-EVT-_SF/
    - assets/products/QF-MAC-ADSW/
    - assets/products/QF-MAC-BC/
    - assets/products/QF-MAC-FOLT/
    - assets/products/QF-MAC-KISW/
    - assets/products/QF-MBC-SET-2/
    - assets/products/QF-PAR-C10/
    - assets/products/QF-PAR-FOF/
    - assets/products/QF-PAR-SET-2/
    - assets/products/QF-PAR-SET-3/
    - assets/products/QF-PAR-SF-1/
    - assets/products/QF-PRB13/
    - assets/products/QF-SAG_02-2S/
    - assets/products/QF-SAG_02-C12/
    - assets/products/QF-SAI-4PC/
    - assets/products/QF-ST-STOOL-WH/
    - assets/products/QF-ST-STOOL-WH-1/
    - assets/data/
    - assets/data/products.json
    - assets/dummy_data.json